### ISSUE TITLE
Card still implement ICard interface

### ISSUE THREAD

**Issue by SergeyTeplyakov** [iamraybell/CsharpBlackJack#4]
Its time for that interface to die.

**Comment by liftcodespike** [comment]
I don't understand this one. If I remove ICard, then everywhere I had Icard I would replace with Card?
Wouldn't this be a case of programming to a implementation, not an interface?

Above all others, this one I would love for you to spend time with me on later. I wanna make sure I understand the reasoning, so I can utilize it fully in the future.  :)

**Comment by SergeyTeplyakov** [comment]
No, it is just fine. Card contains the data and remember I've mentioned about "volatile" classes? If the class contains data it makes no sense to have an interface. So I reopen this one.
