### ISSUE TITLE
Cover GetEnumDescription in unit test

### ISSUE THREAD

**Issue by SergeyTeplyakov** [iamraybell/CsharpBlackJack#7]
Advanced part: given your `CardName` enum, can you still get a name that is not part of the enum?

Here is what I meant: `GetEnumDescription` has the following code:

```csharp
if (attributes.Length > 0) {
                return attributes[0].Description;
            } else {
                return value.ToString();
            }
```

How can you write a test to execute the `else` block?

**Comment by iamraybell** [comment]
This has been resolved. I 100 percent agree with this. The question I have is there is a wrapper (getString) function that executes this, so is it still necessary to rename this if getString is the only one that should be calling it?

**Comment by liftcodespike** [comment]
resolved.
